RANDOM_TREE_COUNT = 20

CAMERA_LENS = 33.3
CAMERA_CLIP_START = 0.1
CAMERA_CLIP_END = 70000
SAMPLES_PER_PIXEL = 16
RENDER_TIME_LIMIT = 222
# RENDER_TILE_SIZE = 4096
RENDER_THREAD_COUNT = 8

CAMERA_ENABLE_VIEW_CULLING = False
CAMERA_ENABLE_BACKFACE_CULLING = False

SIMULATION_FPS = 24
CAMERA_ANIMATION_SPEED_KMH = 60
CAMERA_ANIMATION_SPEED_M_S = CAMERA_ANIMATION_SPEED_KMH / 3.6
MAX_FRAMES = 240
RESOLUTION_X = 400

MAIN_BLEND_FILE = "output/trains.blend"

GEOMETRY_INPUT_FILE = 'output/trains.blend'
# GEOMETRY_INPUT_FILE = 'cube/tmp/geometry.blend'
GEOMETRY_SAVE_FILE = 'cube/geometry.blend'
# GEOMETRY_SAVE_FILE_2 = 'cube/saved-geometry-2.blend'
